### PR TITLE
Removed references from mariadb container

### PR DESCRIPTION
**Pull request by RadZaeem**
Here is the branch I made with `git checkout -b`

### CODE REVIEW

**Comment by dashohoxha** [comment]
- Change the subject of the PR.
- Remove any referencies to mysql, squid, etc.

**Comment by RadZaeem** [comment]
OK done.

**Comment by dashohoxha** [comment]
So, this is how you get things done?
Would you like to make any further changes before you ask me to finally review it?

**Comment by RadZaeem** [comment]
I think for now no further changes.

**Review by dashohoxha — COMMENTED** [review]
It does not work.
Make it work first and submit it again.

**Comment by RadZaeem** [comment]
> It does not work.
> Make it work first and submit it again.

OK I just pushed new commit.
Do you have error logs, where it does not work in your machine?

I have just reset everything with `docker system prune` and rebuild the container from scratch.
It works in my machine.

my history trace:
```
sudo su
ds pull redis fix-container
ds init redis-fix-container @redis
cd /var/ds/redis
ds build
ds create
ds config
ds shell
redis-cli -h redis
ping
```
output
```
redis root@redis:/host
==> # redis-cli -h redis
redis:6379> ping
PONG
redis:6379> 

```

**Comment by dashohoxha** [comment]
> Do you have error logs, where it does not work in your machine?

You are being paid for this job, not me. I am doing it for fun, voluntarily.
If I feel that you want me to do the job for you, it is not fun anymore.

I have adviced you to test and study all the other applications, before doing this one.
But obviously you do not find my advises useful. If you did what I asked you, you would have been able to do this application properly, instead of asking me on each step what to do.

I can advice you towards the right direction, but I cannot tell you everything that you should do.
I cannot spend on this project more time than you do. It doesn't work that way.

**Comment by RadZaeem** [comment]
But it works perfectly on my machine. Am my missing something? What should do differently now?

I can't go anywhere if I don't know slightest hint to reproduce the bug that really didn't exist on my machine.

**Comment by dashohoxha** [comment]
Even if it works, you are not doing things properly. I am sure there are plenty of redis docker containers out  there and they all work. But they are not docker-scripts containers/applications.

In order to do things properly you have to test and study the existing docker-scripts applications, because just reading the man page or looking at its code is not enough to get an idea on how to do things properly. Looking at some examples is much more useful.

I will accept this PR for the time being, but don't consider this application done. You should finish studying all the other applications and will come back again to fix and improve this one.

Testing it from inside the container is not enough. I have asked you to build another container that actually needs to use Redis, in order to be able to test it properly. If you cannot come up with such an application, then really you should choose to build another application instead of Redis. Because an untested application, that does not work well or that has unanticipated problems, is actually worse than no application at all. This is true for any kind of application or service.

Don't expect other people to discover and fix the problems that you could have discovered and fixed yourself. Also, don't build for other people something that you don't need to use yourself.

**Review by dashohoxha — APPROVED** [review]
Accepting for the time being, expecting that it will be fixed and improved later.

**Comment by RadZaeem** [comment]
Thank you for your comments. 
Currently I do not have other ds app to properly tes tredis

Can I choose other app to containerize?

I propose to containerize hugo static page generator.

**Comment by dashohoxha** [comment]
I replied on the issue.

**Pull request merged**
